### ISSUE TITLE
Main features development

### ISSUE THREAD

**Issue by luisberns** [luisberns/atomic-styleguide#1]
Issue to tracking the development of main features to be developed first within this version of this template.

### Todo
- [ ] Add base routes and side pane menu 
- [ ] Develop base components for pages structure
- [ ] Create `index.vue` pages for base structure content
