### ISSUE TITLE
Deploy pages and update info

### ISSUE THREAD

**Issue by luisberns** [luisberns/atomic-styleguide#3]
### Todo
- [ ] Deploy page and update GitHub's description
- [ ] Test new deploy and update usage info
- [ ] Update README documentation
